inherits = "snazzy"

# "diagnostic.error" = { underine = { color = "background1" }}

"ui.background" = { bg = "background1" }
"ui.cursorline.primary" = { bg = "background2p" }
"ui.cursorline.secondary" = { bg = "background2s" }
"ui.popup" = { bg = "background2s" }
"ui.menu" = { bg = "background2s" }
"ui.statusline" = { bg = "background2s" }
"ui.statusline.inactive" = { bg = "background1" }

[palette]

# Purple mode
background1 = "#100020"
background2p = "#201060"
background2s = "#300060"

# Green mode
# background1  = "#003300"
# background2p = "#008800"
# background2s = "#006600"

# Blue mode
# background1  = "#000033"
# background2p = "#000088"
# background2s = "#000066"
